// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projeto.WebAPI.Data;

namespace projeto.WebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190902133124_commit1")]
    partial class commit1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("projeto.WebAPI.Models.GameAccount", b =>
                {
                    b.Property<int>("Account_ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Account_Birthday");

                    b.Property<string>("Account_Email");

                    b.Property<string>("Account_Password");

                    b.Property<string>("Account_Telephone");

                    b.Property<string>("Account_Username");

                    b.HasKey("Account_ID");

                    b.ToTable("GameAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
